
language: python
python:
  - "3.6"
before_install:
  - sudo apt-get install graphviz
install:
  - pip install -r requirements.txt
stages:
  - unittests
  - linter
jobs:
  include:
    - stage: unittests
      name: "Unit Tests"
      script:
        - cd src/lyra/unittests/
        - PYTHONPATH="${PYTHONPATH}:../../"
        - export PYTHONPATH
        - python -m unittest test_SignLattice.py
        - python -m unittest test_IntervalLattice.py
        - python -m unittest test_UsageLattice.py
        - python sign_tests.py
        - python interval_tests.py
        - python liveness_tests.py
        - python usage_tests.py
        - python assumption_tests.py
        - python fulara_tests.py
    - stage: linter
      name: "PEP 8 Coding Style"
      script:
        - cd src/
        - pycodestyle --filename=*.py .
