
language: python
python:
  - "3.6"
before_install:
  - sudo apt-get install graphviz
install:
  - pip install -r requirements.txt
stages:
  - unittests
  - linter
jobs:
  include:
    - stage: unittests
      name: "Unit Tests"
      script:
        - cd src/lyra/unittests/
        - PYTHONPATH="${PYTHONPATH}:../../"
        - export PYTHONPATH
        - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
        - sudo ldconfig
        - python -m unittest test_SignLattice.py
        - python -m unittest test_IntervalLattice.py
        - python -m unittest test_UsageLattice.py
        - python sign_tests.py
        - python interval_tests.py
        - python liveness_tests.py
        - python usage_tests.py
        - python assumption_tests.py
        - python fulara_tests.py
    - stage: linter
      name: "PEP 8 Coding Style"
      script:
        - cd src/
        - pycodestyle --filename=*.py .
    - stage: elina
      name: "Install ELINA"
      script:
        - sudo apt-get install m4
        - wget https://gmplib.org/download/gmp/gmp-6.1.2.tar.xz
        - tar -xvf gmp-6.1.2.tar.xz
        - cd gmp-6.1.2
        - ./configure --enable-cxx
        - make
        - sudo make install
        - wget https://www.mpfr.org/mpfr-current/mpfr-4.0.1.tar.xz
        - tar -xvf mpfr-4.0.1.tar.xz
        - cd mpfr-4.0.1
        - ./configure
        - make
        - sudo make install
        - git clone https://github.com/eth-sri/ELINA.git
        - cd ELINA
        - ./configure
        - make
        - sudo make install
