# INITIAL: a -> W, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> W, weight -> W, score_occurrences -> {([-inf, inf], W)}, scores -> {}
scores: Dict[int, int] = input()     #dictinput()   # id -> score
# STATE: a -> W, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> W, weight -> W, score_occurrences -> {([-inf, inf], W)}, scores -> {}
score_occurrences: Dict[int, int] = {}        # defaultdict(int)    # initialized to 0
# STATE: a -> W, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> W, weight -> W, score_occurrences -> {([-inf, inf], U)}, scores -> {}
for a, b in scores.items():
    # STATE: a -> U, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> N, weight -> W, score_occurrences -> {([-inf, inf], U)}, scores -> {} | a -> W, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> W, weight -> W, score_occurrences -> {([-inf, inf], U)}, scores -> {}
    a = a
    # STATE: a -> U, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> N, weight -> W, score_occurrences -> {([-inf, inf], U)}, scores -> {} | a -> W, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> W, weight -> W, score_occurrences -> {([-inf, inf], U)}, scores -> {}
    if a < 100:     # 'early adopter'
        # STATE: a -> S, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> N, weight -> W, score_occurrences -> {([-inf, inf], S)}, scores -> {} | a -> U, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> N, weight -> U, score_occurrences -> {([-inf, inf], U)}, scores -> {} | a -> W, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> W, weight -> W, score_occurrences -> {([-inf, inf], U)}, scores -> {}
        weight: int = 3
        # STATE: a -> S, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> N, weight -> S, score_occurrences -> {([-inf, inf], S)}, scores -> {} | a -> U, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> N, weight -> U, score_occurrences -> {([-inf, inf], U)}, scores -> {} | a -> W, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> W, weight -> W, score_occurrences -> {([-inf, inf], U)}, scores -> {}
    else:
        # STATE: a -> S, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> N, weight -> W, score_occurrences -> {([-inf, inf], S)}, scores -> {} | a -> U, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> N, weight -> U, score_occurrences -> {([-inf, inf], U)}, scores -> {} | a -> W, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> W, weight -> W, score_occurrences -> {([-inf, inf], U)}, scores -> {}
        weight: int = 1
        # STATE: a -> S, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> N, weight -> S, score_occurrences -> {([-inf, inf], S)}, scores -> {} | a -> U, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> N, weight -> U, score_occurrences -> {([-inf, inf], U)}, scores -> {} | a -> W, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> W, weight -> W, score_occurrences -> {([-inf, inf], U)}, scores -> {}
    # STATE: a -> U, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> N, weight -> U, score_occurrences -> {([-inf, inf], U)}, scores -> {} | a -> W, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> W, weight -> W, score_occurrences -> {([-inf, inf], U)}, scores -> {}
    a = a
    # STATE: a -> U, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> N, weight -> U, score_occurrences -> {([-inf, inf], U)}, scores -> {} | a -> W, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> W, weight -> W, score_occurrences -> {([-inf, inf], U)}, scores -> {}
    if a not in score_occurrences.keys():        # workaround for defaultdict
        # STATE: a -> U, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> N, weight -> S, score_occurrences -> {([-inf, inf], U)}, scores -> {} | a -> U, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> N, weight -> U, score_occurrences -> {([-inf, inf], U)}, scores -> {} | a -> W, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> W, weight -> W, score_occurrences -> {([-inf, inf], U)}, scores -> {}
        score_occurrences[a] = 0
        # STATE: a -> S, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> N, weight -> S, score_occurrences -> {([-inf, inf], S)}, scores -> {} | a -> U, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> N, weight -> U, score_occurrences -> {([-inf, inf], U)}, scores -> {} | a -> W, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> W, weight -> W, score_occurrences -> {([-inf, inf], U)}, scores -> {}
    # STATE: a -> U, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> N, weight -> U, score_occurrences -> {([-inf, inf], U)}, scores -> {} | a -> W, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> W, weight -> W, score_occurrences -> {([-inf, inf], U)}, scores -> {}
    score_occurrences[a] += weight   # BUG A: should be indexed by b
    # STATE: a -> N, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> N, weight -> N, score_occurrences -> {([-inf, inf], S)}, scores -> {} | a -> W, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> W, weight -> W, score_occurrences -> {([-inf, inf], U)}, scores -> {}
# STATE: a -> N, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> W, weight -> N, score_occurrences -> {([11, inf], U)}, scores -> {}
scores_gt_10: int = 0
# STATE: a -> N, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> U, weight -> N, score_occurrences -> {([11, inf], U)}, scores -> {}
for k in score_occurrences.keys():
    # STATE: a -> N, b -> N, k -> U, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> U, weight -> N, score_occurrences -> {([11, inf], U)}, scores -> {} | a -> N, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> U, weight -> N, score_occurrences -> {([11, inf], U)}, scores -> {}
    a = a
    # STATE: a -> N, b -> N, k -> U, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> U, weight -> N, score_occurrences -> {([11, inf], U)}, scores -> {} | a -> N, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> U, weight -> N, score_occurrences -> {([11, inf], U)}, scores -> {}
    if k > 10:
        # STATE: a -> N, b -> N, k -> U, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> U, weight -> N, score_occurrences -> {([11, inf], U)}, scores -> {} | a -> N, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> S, weight -> N, score_occurrences -> {([11, inf], S)}, scores -> {} | a -> N, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> U, weight -> N, score_occurrences -> {([11, inf], U)}, scores -> {}
        scores_gt_10 += score_occurrences[k]
        # STATE: a -> N, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> S, weight -> N, score_occurrences -> {([11, inf], S)}, scores -> {} | a -> N, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> S, weight -> N, score_occurrences -> {([11, inf], S)}, scores -> {} | a -> N, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> U, weight -> N, score_occurrences -> {([11, inf], U)}, scores -> {}
    # STATE: a -> N, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> S, weight -> N, score_occurrences -> {([11, inf], S)}, scores -> {} | a -> N, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> U, weight -> N, score_occurrences -> {([11, inf], U)}, scores -> {}
    a = a
    # STATE: a -> N, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> S, weight -> N, score_occurrences -> {([11, inf], S)}, scores -> {} | a -> N, b -> N, k -> W, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> U, weight -> N, score_occurrences -> {([11, inf], U)}, scores -> {}
# STATE: a -> N, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> U, weight -> N, score_occurrences -> {}, scores -> {}
print(scores_gt_10)
# FINAL: a -> N, b -> N, k -> N, len(score_occurrences) -> N, len(scores) -> N, scores_gt_10 -> N, weight -> N, score_occurrences -> {}, scores -> {}
